### ISSUE TITLE
need player names and their champion in the teams section

### ISSUE THREAD

**Issue by NullCodex** [timewindergg/Rewind#6]

**Comment by tyuo9980** [comment]
is already available in red_team and blue_team json fields

**Comment by NullCodex** [comment]
not the champion names

**Comment by tyuo9980** [comment]
champion ids are available. should be able to map them to names

**Comment by NullCodex** [comment]
no, what im saying is that you are not championIds either so I have no way of getting the champion icon or names.

**Comment by tyuo9980** [comment]
dnp
